--------------------------------------------------------
--  文件已创建 - 星期一-八月-07-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table B_BASICINFO
--------------------------------------------------------

  CREATE TABLE "B_BASICINFO" 
   (	"ID" NUMBER(11,0), 
	"SW_CODE" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(64 BYTE), 
	"CATEGORY" VARCHAR2(64 BYTE), 
	"MODULE_RELATION" VARCHAR2(64 BYTE), 
	"DEPARTMENT" VARCHAR2(64 BYTE), 
	"SW_OWNER" VARCHAR2(20 BYTE), 
	"SW_SYSTEM" VARCHAR2(64 BYTE), 
	"INSTALLPOS" VARCHAR2(64 BYTE), 
	"SW_STORAGE" VARCHAR2(100 BYTE) DEFAULT '0', 
	"SW_SAVEPOS" VARCHAR2(64 BYTE), 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"MAKEUNIT" VARCHAR2(2000 BYTE), 
	"SW_ANNEX" VARCHAR2(2000 BYTE), 
	"SW_INFO" VARCHAR2(2000 BYTE), 
	"PID" VARCHAR2(20 BYTE), 
	"SW_VERSION" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE, 
	"MD5" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "B_BASICINFO"."NAME" IS '软件名称';
 
   COMMENT ON COLUMN "B_BASICINFO"."CATEGORY" IS '软件谱系';
 
   COMMENT ON COLUMN "B_BASICINFO"."MODULE_RELATION" IS '软件模块关系';
 
   COMMENT ON COLUMN "B_BASICINFO"."DEPARTMENT" IS '研制单位';
 
   COMMENT ON COLUMN "B_BASICINFO"."SW_OWNER" IS '军代表';
 
   COMMENT ON COLUMN "B_BASICINFO"."SW_SYSTEM" IS '操作系统';
 
   COMMENT ON COLUMN "B_BASICINFO"."INSTALLPOS" IS '典型安装位置';
 
   COMMENT ON COLUMN "B_BASICINFO"."SW_STORAGE" IS '存储方式';
 
   COMMENT ON COLUMN "B_BASICINFO"."SW_SAVEPOS" IS '存储位置';
 
   COMMENT ON COLUMN "B_BASICINFO"."STATUS" IS '激活';
 
   COMMENT ON COLUMN "B_BASICINFO"."SW_ANNEX" IS '附件';
 
   COMMENT ON COLUMN "B_BASICINFO"."SW_INFO" IS '软件描述';
 
   COMMENT ON COLUMN "B_BASICINFO"."SW_VERSION" IS '软件版本';
--------------------------------------------------------
--  DDL for Table B_CATEGORY
--------------------------------------------------------

  CREATE TABLE "B_CATEGORY" 
   (	"ID" NUMBER(11,0), 
	"SU_CODE" VARCHAR2(64 BYTE), 
	"SU_NAME" VARCHAR2(20 BYTE), 
	"SUPERIOR_ID" NUMBER(11,20), 
	"SW_NAME" VARCHAR2(20 BYTE), 
	"SW_MODULE" VARCHAR2(64 BYTE), 
	"DEPARTMENT" VARCHAR2(64 BYTE), 
	"SU_OWNERID" VARCHAR2(20 BYTE), 
	"SU_SYSTEM" VARCHAR2(20 BYTE), 
	"INSTALLPOS" VARCHAR2(64 BYTE), 
	"SU_STORAGE" NUMBER, 
	"SU_SAVEPOS" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT NULL, 
	"SU_ANNEX" VARCHAR2(64 BYTE), 
	"SU_DESCRIBE" VARCHAR2(2000 BYTE), 
	"UPDATETIME" DATE, 
	"CREATETIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "B_CATEGORY"."SU_NAME" IS '软件单元名称';
 
   COMMENT ON COLUMN "B_CATEGORY"."SUPERIOR_ID" IS '上级ID';
 
   COMMENT ON COLUMN "B_CATEGORY"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "B_CATEGORY"."SW_MODULE" IS '谱系';
 
   COMMENT ON COLUMN "B_CATEGORY"."DEPARTMENT" IS '研制单位';
 
   COMMENT ON COLUMN "B_CATEGORY"."SU_OWNERID" IS '军代表';
 
   COMMENT ON COLUMN "B_CATEGORY"."SU_SYSTEM" IS '操作系统';
 
   COMMENT ON COLUMN "B_CATEGORY"."INSTALLPOS" IS '安装位置';
 
   COMMENT ON COLUMN "B_CATEGORY"."SU_STORAGE" IS '存储方式';
 
   COMMENT ON COLUMN "B_CATEGORY"."SU_SAVEPOS" IS '存储位置';
 
   COMMENT ON COLUMN "B_CATEGORY"."STATUS" IS '0可用（激活），1不可用（未激活），2永久删除';
 
   COMMENT ON COLUMN "B_CATEGORY"."SU_ANNEX" IS '附件';
 
   COMMENT ON COLUMN "B_CATEGORY"."SU_DESCRIBE" IS '软件单元描述';
--------------------------------------------------------
--  DDL for Table B_MODULE
--------------------------------------------------------

  CREATE TABLE "B_MODULE" 
   (	"ID" NUMBER(11,0), 
	"NAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"PARENT_ID" VARCHAR2(500 BYTE) DEFAULT NULL, 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_USER" NUMBER(11,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "B_MODULE"."ID" IS '软件谱系ID';
 
   COMMENT ON COLUMN "B_MODULE"."NAME" IS '软件谱系名称';
 
   COMMENT ON COLUMN "B_MODULE"."PARENT_ID" IS '父级谱系 ID';
 
   COMMENT ON COLUMN "B_MODULE"."STATUS" IS '0可用（激活），1不可用（未激活），2永久删除';
--------------------------------------------------------
--  DDL for Table B_UNIT
--------------------------------------------------------

  CREATE TABLE "B_UNIT" 
   (	"ID" NUMBER, 
	"TREE_ID" NUMBER, 
	"SU_BASE_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"SW_OWNER_ID" NUMBER, 
	"SU_CODE" VARCHAR2(64 BYTE), 
	"SU_NAME" VARCHAR2(64 BYTE), 
	"SU_TYPE" VARCHAR2(200 BYTE), 
	"SU_SYSTEM" VARCHAR2(200 BYTE), 
	"SU_LOCATION" VARCHAR2(500 BYTE), 
	"SU_GROUPINFO" VARCHAR2(2000 BYTE), 
	"SU_STORAGE" VARCHAR2(500 BYTE), 
	"SU_ADDR" VARCHAR2(1000 BYTE), 
	"SU_INFO" VARCHAR2(2000 BYTE), 
	"SU_ANNEX" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"SUPERIOR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "B_UNIT"."ID" IS 'ID';
 
   COMMENT ON COLUMN "B_UNIT"."TREE_ID" IS '谱系ID';
 
   COMMENT ON COLUMN "B_UNIT"."SU_BASE_ID" IS '所属软件ID';
 
   COMMENT ON COLUMN "B_UNIT"."DEPARTMENT_ID" IS '研制单位ID';
 
   COMMENT ON COLUMN "B_UNIT"."SW_OWNER_ID" IS '代表室用户ID';
 
   COMMENT ON COLUMN "B_UNIT"."SU_CODE" IS '软件单元编号';
 
   COMMENT ON COLUMN "B_UNIT"."SU_NAME" IS '软件单元名称';
 
   COMMENT ON COLUMN "B_UNIT"."SU_TYPE" IS '软件类型';
 
   COMMENT ON COLUMN "B_UNIT"."SU_SYSTEM" IS '操作系统';
 
   COMMENT ON COLUMN "B_UNIT"."SU_LOCATION" IS '安装位置';
 
   COMMENT ON COLUMN "B_UNIT"."SU_GROUPINFO" IS '配套软件';
 
   COMMENT ON COLUMN "B_UNIT"."SU_STORAGE" IS '存储方式';
 
   COMMENT ON COLUMN "B_UNIT"."SU_ADDR" IS '存放位置';
 
   COMMENT ON COLUMN "B_UNIT"."SU_INFO" IS '软件单元信息';
 
   COMMENT ON COLUMN "B_UNIT"."SU_ANNEX" IS '附件信息';
 
   COMMENT ON COLUMN "B_UNIT"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "B_UNIT"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "B_UNIT"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "B_UNIT"."UPDATE_ID" IS '更新人员';
 
   COMMENT ON COLUMN "B_UNIT"."STATUS" IS '0可用（激活），1不可用（未激活），2永久删除';
 
   COMMENT ON COLUMN "B_UNIT"."SUPERIOR_ID" IS '上级单元ID';
--------------------------------------------------------
--  DDL for Table B_USER
--------------------------------------------------------

  CREATE TABLE "B_USER" 
   (	"ID" NUMBER(11,0), 
	"ORGANIZATION_ID" NUMBER(11,0) DEFAULT NULL, 
	"ROLE_ID" NUMBER(11,0) DEFAULT NULL, 
	"AVATAR" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"REAL_NAME" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"TELEPHONE" VARCHAR2(18 BYTE) DEFAULT NULL, 
	"Mobile" VARCHAR2(18 BYTE) DEFAULT NULL, 
	"GENDER" NUMBER(1,0) DEFAULT 0, 
	"EMAIL" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"ADDRESS" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"BIRTHDAY" DATE DEFAULT NULL, 
	"QQ" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"WECHAT" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"REMARK" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"LOGIN_NAME" VARCHAR2(200 BYTE), 
	"CREATE_USER_ID" NUMBER(11,0) DEFAULT NULL, 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_USER" NUMBER(11,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Table P_DAILY_REGISTER
--------------------------------------------------------

  CREATE TABLE "P_DAILY_REGISTER" 
   (	"ID" NUMBER, 
	"CODE" VARCHAR2(200 BYTE), 
	"REGISTER" VARCHAR2(100 BYTE), 
	"REGISTER_UNIT" VARCHAR2(200 BYTE), 
	"REGISTER_TITLE" VARCHAR2(200 BYTE), 
	"SW_MODULE" VARCHAR2(2000 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"FAILURE_LEVEL" VARCHAR2(200 BYTE), 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"DEFAULT_TIME" DATE, 
	"REGISTE_TYPE" NUMBER, 
	"DEFAULT_ISOK" NUMBER, 
	"ANNEX" VARCHAR2(200 BYTE), 
	"DESCRIBE_INFO" VARCHAR2(2000 BYTE), 
	"DEFAULT_DESCRIBE" VARCHAR2(2000 BYTE), 
	"SOLVE_METHOD" VARCHAR2(2000 BYTE), 
	"CREATE_DATA" DATE, 
	"CREATOR_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"STATUS" NUMBER, 
	"REGISTER_SUMMARY_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_DAILY_REGISTER"."ID" IS '唯一id标识';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."CODE" IS '编号';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."REGISTER" IS '登记人';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."REGISTER_UNIT" IS '登记单位';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."REGISTER_TITLE" IS '日常登记标题';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."SW_MODULE" IS '软件谱系';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."FAILURE_LEVEL" IS '故障等级';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."BEGIN_TIME" IS '开机时间';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."END_TIME" IS '关机时间';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."DEFAULT_TIME" IS '故障时间';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."REGISTE_TYPE" IS '登记类型： 0代表日常登记，1代表故障排查。';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."DEFAULT_ISOK" IS '故障是否解决：0代表解决，1代表未解决';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."DESCRIBE_INFO" IS '描述信息';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."DEFAULT_DESCRIBE" IS '故障描述';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."SOLVE_METHOD" IS '解决办法';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."CREATE_DATA" IS '创建日期';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."CREATOR_ID" IS '创建人';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."UPDATE_DATE" IS '更新日期';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."UPDATE_ID" IS '更新人员';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "P_DAILY_REGISTER"."REGISTER_SUMMARY_ID" IS '汇总信息ID';
--------------------------------------------------------
--  DDL for Table P_DEPLOYAPPLY
--------------------------------------------------------

  CREATE TABLE "P_DEPLOYAPPLY" 
   (	"ID" NUMBER, 
	"ODD_CODE" VARCHAR2(100 BYTE), 
	"APPLICANT_UID" NUMBER, 
	"APPLICANT_UNIT_ID" NUMBER, 
	"HANDLE_UID" NUMBER, 
	"TASK_ID" NUMBER, 
	"AUDIT_UID" NUMBER, 
	"ADJUNCT" VARCHAR2(2000 BYTE), 
	"EXPLAIN" VARCHAR2(2000 BYTE), 
	"SW_ID" NUMBER, 
	"TREE_ID" NUMBER, 
	"SW_DES" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"STATUS" VARCHAR2(1 BYTE), 
	"FLOW_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_DEPLOYAPPLY"."ID" IS 'ID';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."ODD_CODE" IS '单号';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."APPLICANT_UID" IS '申请人ID';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."APPLICANT_UNIT_ID" IS '申请单位ID';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."HANDLE_UID" IS '处理人ID';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."TASK_ID" IS '任务来源ID';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."AUDIT_UID" IS '审核人ID';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."ADJUNCT" IS '附件';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."EXPLAIN" IS '说明';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."SW_ID" IS '软件ID';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."TREE_ID" IS '谱系ID';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."SW_DES" IS '软件描述';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."UPDATE_ID" IS '更新人员';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."STATUS" IS '状态： 0，可用，
1， 不可用';
 
   COMMENT ON COLUMN "P_DEPLOYAPPLY"."FLOW_ID" IS '流程ID';
--------------------------------------------------------
--  DDL for Table P_DEPLOY_SCHEMA
--------------------------------------------------------

  CREATE TABLE "P_DEPLOY_SCHEMA" 
   (	"ID" NUMBER, 
	"ODD_CODE" VARCHAR2(100 BYTE), 
	"UNIT_ID" NUMBER, 
	"NAME" VARCHAR2(1000 BYTE), 
	"TASK_ID" NUMBER, 
	"SW_ID" NUMBER, 
	"TREE_ID" NUMBER, 
	"RELE_DOC" VARCHAR2(2000 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"HANDLE_UID" NUMBER, 
	"ALLOC_UID" NUMBER, 
	"EXPLAIN" VARCHAR2(2000 BYTE), 
	"APPLY_LIST" VARCHAR2(2000 BYTE), 
	"DETIAL" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"FLOW_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."ID" IS 'ID';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."ODD_CODE" IS '编号';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."UNIT_ID" IS '制定单位ID';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."NAME" IS '方案名称';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."TASK_ID" IS '任务来源ID';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."SW_ID" IS '软件ID';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."TREE_ID" IS '谱系ID';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."RELE_DOC" IS '相关文件';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."DESCRIPTION" IS '方案描述';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."HANDLE_UID" IS '处理人ID';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."ALLOC_UID" IS '任务分配人ID';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."EXPLAIN" IS '说明';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."APPLY_LIST" IS '调配申请列表（
括号逗号隔开：
（1, 2, 3）
）';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."DETIAL" IS '调配方案详情（
  json字符串
）';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."UPDATE_ID" IS '更新人员';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."STATUS" IS '状态： 0，可用
1， 不可用';
 
   COMMENT ON COLUMN "P_DEPLOY_SCHEMA"."FLOW_ID" IS '流程ID';
--------------------------------------------------------
--  DDL for Table P_EXPORTAPPLY
--------------------------------------------------------

  CREATE TABLE "P_EXPORTAPPLY" 
   (	"ID" NUMBER, 
	"EXPORTAPPLY_CODE" VARCHAR2(100 BYTE), 
	"APPLICANT_UID" NUMBER, 
	"APPLICANT_UNIT_ID" NUMBER, 
	"HANDLE_UID" NUMBER, 
	"TASH_ID" NUMBER, 
	"AUDIT_UID" NUMBER, 
	"ADJUNCT" VARCHAR2(2000 BYTE), 
	"DESCRPTION" VARCHAR2(2000 BYTE), 
	"SW_ID" NUMBER, 
	"TREE_ID" NUMBER, 
	"SW_VERSION" VARCHAR2(1000 BYTE), 
	"INS_UNIT_ID" NUMBER, 
	"SW_MODULE_RELA" VARCHAR2(2000 BYTE), 
	"SYSTEM" VARCHAR2(500 BYTE), 
	"INS_LOC" VARCHAR2(2000 BYTE), 
	"SW_GROUPINFO" VARCHAR2(2000 BYTE), 
	"SW_GRADE" VARCHAR2(1000 BYTE), 
	"STORAGE_TYPE" VARCHAR2(500 BYTE), 
	"MD5" VARCHAR2(100 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"FLOW_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_EXPORTAPPLY"."ID" IS 'ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."EXPORTAPPLY_CODE" IS '单号';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."APPLICANT_UID" IS '申请人ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."APPLICANT_UNIT_ID" IS '申请单位ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."HANDLE_UID" IS '处理人ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."TASH_ID" IS '任务来源ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."AUDIT_UID" IS '选择审核人ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."ADJUNCT" IS '附件';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."DESCRPTION" IS '说明';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."SW_ID" IS '软件ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."TREE_ID" IS '谱系ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."SW_VERSION" IS '软件版本';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."INS_UNIT_ID" IS '安装单位ID';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."SW_MODULE_RELA" IS '软件模块关系';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."SYSTEM" IS '操作系统';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."INS_LOC" IS '典型安装位置';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."SW_GROUPINFO" IS '配套软件';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."SW_GRADE" IS '软件等级';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."STORAGE_TYPE" IS '存储方式';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."MD5" IS 'MD5校验值';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."UPDATE_ID" IS '更新人员';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."STATUS" IS '状态：0，可用
1，不可以';
 
   COMMENT ON COLUMN "P_EXPORTAPPLY"."FLOW_ID" IS '流程ID';
--------------------------------------------------------
--  DDL for Table P_HISTORY_RECORD
--------------------------------------------------------

  CREATE TABLE "P_HISTORY_RECORD" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(200 BYTE), 
	"OPERATOR" VARCHAR2(200 BYTE), 
	"TIME" DATE, 
	"STATE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_HISTORY_RECORD"."TYPE" IS '类型';
 
   COMMENT ON COLUMN "P_HISTORY_RECORD"."OPERATOR" IS '操作人';
 
   COMMENT ON COLUMN "P_HISTORY_RECORD"."TIME" IS '时间';
 
   COMMENT ON COLUMN "P_HISTORY_RECORD"."STATE" IS '状态';
--------------------------------------------------------
--  DDL for Table P_ONLINE_HELP
--------------------------------------------------------

  CREATE TABLE "P_ONLINE_HELP" 
   (	"ID" NUMBER, 
	"NUMBER" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"CREATOR" VARCHAR2(200 BYTE), 
	"FORMULATE_UNIT" VARCHAR2(200 BYTE), 
	"SW_MODULE" VARCHAR2(200 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"RELATIVE_SCHEME" VARCHAR2(1000 BYTE), 
	"ANNEX" VARCHAR2(200 BYTE), 
	"DESCRIBE_INFO" VARCHAR2(2000 BYTE), 
	"PHENOMENON_DESCRIBE" VARCHAR2(2000 BYTE), 
	"OPERATE_INFO" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_ONLINE_HELP"."NUMBER" IS '编号';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."NAME" IS '名称';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."CREATOR" IS '制定人';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."FORMULATE_UNIT" IS '制定单位';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."SW_MODULE" IS '软件谱系';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."RELATIVE_SCHEME" IS '相关技术保障方案';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."DESCRIBE_INFO" IS '描述信息';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."PHENOMENON_DESCRIBE" IS '现象说明';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."OPERATE_INFO" IS '操作信息';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_ONLINE_HELP"."UPDATE_ID" IS '更新人员';
--------------------------------------------------------
--  DDL for Table P_PLAN
--------------------------------------------------------

  CREATE TABLE "P_PLAN" 
   (	"ID" NUMBER, 
	"PLAN_NAME" VARCHAR2(64 BYTE), 
	"STATE" NUMBER(1,0), 
	"PLAN_DESCRIBE" VARCHAR2(1000 BYTE), 
	"CREATE_DATA" DATE, 
	"CREATOR_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_PLAN"."STATE" IS '状态';
 
   COMMENT ON COLUMN "P_PLAN"."PLAN_DESCRIBE" IS '计划描述';
 
   COMMENT ON COLUMN "P_PLAN"."CREATE_DATA" IS '创建日期';
 
   COMMENT ON COLUMN "P_PLAN"."CREATOR_ID" IS '创建人';
 
   COMMENT ON COLUMN "P_PLAN"."UPDATE_DATE" IS '更新日期';
 
   COMMENT ON COLUMN "P_PLAN"."UPDATE_ID" IS '更新人员';
--------------------------------------------------------
--  DDL for Table P_PLAN_STAGE
--------------------------------------------------------

  CREATE TABLE "P_PLAN_STAGE" 
   (	"ID" NUMBER, 
	"STAGE_NAME" VARCHAR2(200 BYTE), 
	"STAGE_TYPE" VARCHAR2(200 BYTE), 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"STAGE_DESCRIBE" VARCHAR2(2000 BYTE), 
	"HANDLER" VARCHAR2(200 BYTE), 
	"REMIND" VARCHAR2(32 BYTE), 
	"CREATE_DATA" DATE, 
	"CREATOR_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"STATUS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_PLAN_STAGE"."STAGE_NAME" IS '计划名称';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."STAGE_TYPE" IS '计划类型';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."BEGIN_TIME" IS '阶段开始时间';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."END_TIME" IS '阶段结束时间';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."STAGE_DESCRIBE" IS '阶段描述';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."HANDLER" IS '处理人';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."REMIND" IS '是否提醒';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."CREATE_DATA" IS '创建日期';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."CREATOR_ID" IS '创建人';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."UPDATE_DATE" IS '更新日期';
 
   COMMENT ON COLUMN "P_PLAN_STAGE"."STATUS" IS '状态';
--------------------------------------------------------
--  DDL for Table P_REGISTER_SUMMARY
--------------------------------------------------------

  CREATE TABLE "P_REGISTER_SUMMARY" 
   (	"ID" NUMBER, 
	"CODE" NUMBER, 
	"STATE" VARCHAR2(200 BYTE), 
	"SUMMARY_TYPY" VARCHAR2(200 BYTE), 
	"DESCRIBE_INFO" VARCHAR2(2000 BYTE), 
	"ANNEX" VARCHAR2(200 BYTE), 
	"SUMMARY_UNIT" VARCHAR2(200 BYTE), 
	"COLLECTOR" VARCHAR2(200 BYTE), 
	"SW_MODULE" VARCHAR2(500 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"FAULT_LEVEL" NUMBER, 
	"DUFAULT_ISOK" NUMBER, 
	"DAILY_REGISTER_ID" NUMBER, 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"TECHNICAL_SUPPORT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."CODE" IS '编号';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."STATE" IS '状态';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."SUMMARY_TYPY" IS '汇总类型';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."DESCRIBE_INFO" IS '描述信息';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."SUMMARY_UNIT" IS '汇总单位';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."COLLECTOR" IS '汇总人';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."SW_MODULE" IS '谱系';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."FAULT_LEVEL" IS '故障等级：0表示一般，1表示严重';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."DUFAULT_ISOK" IS '故障是否解决：0表示解决，1表示为解决';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."DAILY_REGISTER_ID" IS '日常登记ID';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_REGISTER_SUMMARY"."UPDATE_ID" IS '更新人员';
 
   COMMENT ON TABLE "P_REGISTER_SUMMARY"  IS '登记汇总';
--------------------------------------------------------
--  DDL for Table P_RETIREAPPLY
--------------------------------------------------------

  CREATE TABLE "P_RETIREAPPLY" 
   (	"ID" NUMBER, 
	"ODD_CODE" VARCHAR2(100 BYTE), 
	"INPUT_REG_UID" NUMBER, 
	"HANDLE_UID" NUMBER, 
	"REG_UNIT_ID" NUMBER, 
	"STORAGE_TYPE" VARCHAR2(1 BYTE), 
	"STORAGE_INFO" VARCHAR2(2000 BYTE), 
	"COMMAND" VARCHAR2(100 BYTE), 
	"MD5" VARCHAR2(100 BYTE), 
	"RELEVANT_DOC" VARCHAR2(2000 BYTE), 
	"INFO_DES" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"FLOW_ID" VARCHAR2(100 BYTE), 
	"Column_18" CHAR(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_RETIREAPPLY"."ID" IS 'ID';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."ODD_CODE" IS '单号';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."INPUT_REG_UID" IS '入库登记人ID';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."HANDLE_UID" IS '处理人ID';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."REG_UNIT_ID" IS '登记单位ID';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."STORAGE_TYPE" IS '存储方式: 1:
自持， 2：网络存储';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."STORAGE_INFO" IS '存储信息';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."COMMAND" IS '提取码';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."MD5" IS 'MD5确认';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."RELEVANT_DOC" IS '相关文件';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."INFO_DES" IS '信息说明';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."UPDATE_ID" IS '更新人员';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."STATUS" IS '状态： 0，可以
1：不可以';
 
   COMMENT ON COLUMN "P_RETIREAPPLY"."FLOW_ID" IS '流程ID';
--------------------------------------------------------
--  DDL for Table P_STORAGEAPPLY
--------------------------------------------------------

  CREATE TABLE "P_STORAGEAPPLY" 
   (	"ID" NUMBER, 
	"SW_ID" NUMBER, 
	"TREE_ID" NUMBER, 
	"SW_GRADE" VARCHAR2(20 BYTE), 
	"SW_UNIT_NAME" VARCHAR2(1000 BYTE), 
	"SW_UNIT_PLATE" VARCHAR2(1000 BYTE), 
	"SW_MOU_RELA" VARCHAR2(1000 BYTE), 
	"INS_LOC" VARCHAR2(1000 BYTE), 
	"SYSTEM" VARCHAR2(500 BYTE), 
	"SW_GROUPINFO" VARCHAR2(2000 BYTE), 
	"CODE_SIZE" VARCHAR2(500 BYTE), 
	"STORAGE_MODE" VARCHAR2(500 BYTE), 
	"MD5" VARCHAR2(100 BYTE), 
	"STORAGE_LOC" VARCHAR2(2000 BYTE), 
	"ADJUNCT" VARCHAR2(2000 BYTE), 
	"SW_DESCRIPTION" VARCHAR2(2000 BYTE), 
	"SW_UNIT_ID" NUMBER, 
	"APPLICANT_UNIT_ID" NUMBER, 
	"APPLICANT_UID" NUMBER, 
	"HANDLE_UID" NUMBER, 
	"AUDIT_UID" NUMBER, 
	"ODD_CODE" VARCHAR2(200 BYTE), 
	"TASK_ID" NUMBER, 
	"EXPLAIN" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" NUMBER, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"FLOW_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_STORAGEAPPLY"."ID" IS 'ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SW_ID" IS '软件ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."TREE_ID" IS '谱系ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SW_GRADE" IS '软件等级:1 公开，2 内部公开， 3 保密， 4
机密，5 秘密';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SW_UNIT_NAME" IS '软件单元名称';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SW_UNIT_PLATE" IS '软件单元版本';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SW_MOU_RELA" IS '软件模块关系';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."INS_LOC" IS '典型安装位置';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SYSTEM" IS '操作系统';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SW_GROUPINFO" IS '配套软件';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."CODE_SIZE" IS '代码规模';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."STORAGE_MODE" IS '存储方式';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."MD5" IS 'MD5校验值';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."STORAGE_LOC" IS '存储位置';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."ADJUNCT" IS '附件';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SW_DESCRIPTION" IS '软件描述';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."SW_UNIT_ID" IS '软件单元ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."APPLICANT_UNIT_ID" IS '申请单位ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."APPLICANT_UID" IS '申请人ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."HANDLE_UID" IS '处理人ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."AUDIT_UID" IS '审核人ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."ODD_CODE" IS '入库申请单号';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."TASK_ID" IS '任务来源ID';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."EXPLAIN" IS '说明';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."UPDATE_ID" IS '更新人员';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."STATUS" IS '状态：0 可以，
1： 不可以';
 
   COMMENT ON COLUMN "P_STORAGEAPPLY"."FLOW_ID" IS '流程ID';
--------------------------------------------------------
--  DDL for Table P_SUPPORT_SCHEME_TASK
--------------------------------------------------------

  CREATE TABLE "P_SUPPORT_SCHEME_TASK" 
   (	"ID" NUMBER, 
	"NUMBER" VARCHAR2(2000 BYTE), 
	"TASK_TYPE" VARCHAR2(200 BYTE), 
	"TASK_DETAIL" VARCHAR2(200 BYTE), 
	"TASK_UNIT" VARCHAR2(200 BYTE), 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"SUPPORT_SCHEME_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_SUPPORT_SCHEME_TASK"."NUMBER" IS '任务编号';
 
   COMMENT ON COLUMN "P_SUPPORT_SCHEME_TASK"."TASK_TYPE" IS '任务类型';
 
   COMMENT ON COLUMN "P_SUPPORT_SCHEME_TASK"."TASK_DETAIL" IS '任务详情';
 
   COMMENT ON COLUMN "P_SUPPORT_SCHEME_TASK"."TASK_UNIT" IS '任务单位';
 
   COMMENT ON COLUMN "P_SUPPORT_SCHEME_TASK"."BEGIN_TIME" IS '开始时间';
 
   COMMENT ON COLUMN "P_SUPPORT_SCHEME_TASK"."END_TIME" IS '结束时间';
 
   COMMENT ON COLUMN "P_SUPPORT_SCHEME_TASK"."SUPPORT_SCHEME_ID" IS '方案id';
--------------------------------------------------------
--  DDL for Table P_TECHNICAL_SUPPORT_REQUEST
--------------------------------------------------------

  CREATE TABLE "P_TECHNICAL_SUPPORT_REQUEST" 
   (	"ID" NUMBER, 
	"CODE" NUMBER, 
	"APPLICANT" VARCHAR2(200 BYTE), 
	"APPLY_UNIT" VARCHAR2(200 BYTE), 
	"APPLY_TITLE" VARCHAR2(200 BYTE), 
	"HANDLER" VARCHAR2(200 BYTE), 
	"TASK_SOURCE" VARCHAR2(200 BYTE), 
	"AUDITOR" VARCHAR2(200 BYTE), 
	"ANNEX" VARCHAR2(200 BYTE), 
	"APPLY_REASON" VARCHAR2(2000 BYTE), 
	"DESCRIBE" VARCHAR2(2000 BYTE), 
	"SW_MUDULE" VARCHAR2(200 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"SW_CATEGORY" VARCHAR2(200 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"TECHNICAL_SCHEME_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."ID" IS '技术保障申请单id';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."CODE" IS '编号';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."APPLICANT" IS '申请人';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."APPLY_UNIT" IS '申请单位';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."APPLY_TITLE" IS '申请标题';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."HANDLER" IS '处理人';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."TASK_SOURCE" IS '任务来源';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."AUDITOR" IS '审核人';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."APPLY_REASON" IS '申请原因';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."DESCRIBE" IS '描述';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."SW_MUDULE" IS '故障软件谱系';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."SW_CATEGORY" IS '软件单元';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_REQUEST"."UPDATE_ID" IS '更新人员';
--------------------------------------------------------
--  DDL for Table P_TECHNICAL_SUPPORT_SCHEME
--------------------------------------------------------

  CREATE TABLE "P_TECHNICAL_SUPPORT_SCHEME" 
   (	"ID" NUMBER, 
	"CODE" NUMBER, 
	"FORMULATE_UNIT" VARCHAR2(200 BYTE), 
	"SCHEME_NAME" VARCHAR2(200 BYTE), 
	"TASK_RESOURCE" VARCHAR2(200 BYTE), 
	"SW_MODULE" VARCHAR2(200 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"ANNEX" VARCHAR2(200 BYTE), 
	"SCHEME_DESCRIBE" VARCHAR2(2000 BYTE), 
	"HANDLER" VARCHAR2(200 BYTE), 
	"TASK_DISTRIBUTOR" VARCHAR2(200 BYTE), 
	"DESCRIBE" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."CODE" IS '编号';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."FORMULATE_UNIT" IS '制定单位';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."SCHEME_NAME" IS '方案名称';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."TASK_RESOURCE" IS '任务来源';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."SW_MODULE" IS '软件谱系';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."SCHEME_DESCRIBE" IS '方案描述';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."HANDLER" IS '处理人';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."TASK_DISTRIBUTOR" IS '任务分配人';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."DESCRIBE" IS '描述';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_TECHNICAL_SUPPORT_SCHEME"."UPDATE_ID" IS '更新人员';
--------------------------------------------------------
--  DDL for Table P_UPGRADE_APPLY
--------------------------------------------------------

  CREATE TABLE "P_UPGRADE_APPLY" 
   (	"ID" NUMBER, 
	"CODE" NUMBER, 
	"APPLICANT" VARCHAR2(200 BYTE), 
	"APPLY_UNIT" VARCHAR2(200 BYTE), 
	"APPLY_TITLE" VARCHAR2(200 BYTE), 
	"HANDLER" VARCHAR2(200 BYTE), 
	"TASK_SOURCE" VARCHAR2(200 BYTE), 
	"AUDITOR" VARCHAR2(200 BYTE), 
	"ANNEX" VARCHAR2(200 BYTE), 
	"APPLY_REASON" VARCHAR2(2000 BYTE), 
	"DESCRIBE" VARCHAR2(2000 BYTE), 
	"SW_MUDULE" VARCHAR2(200 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"SW_CATEGORY" VARCHAR2(200 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"TECHNICAL_SCHEME_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_UPGRADE_APPLY"."ID" IS '技术保障申请单id';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."CODE" IS '编号';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."APPLICANT" IS '申请人';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."APPLY_UNIT" IS '申请单位';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."APPLY_TITLE" IS '申请标题';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."HANDLER" IS '处理人';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."TASK_SOURCE" IS '任务来源';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."AUDITOR" IS '审核人';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."APPLY_REASON" IS '申请原因';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."DESCRIBE" IS '描述';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."SW_MUDULE" IS '故障软件谱系';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."SW_CATEGORY" IS '软件单元';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_UPGRADE_APPLY"."UPDATE_ID" IS '更新人员';
--------------------------------------------------------
--  DDL for Table P_UPGRADE_REQUEST
--------------------------------------------------------

  CREATE TABLE "P_UPGRADE_REQUEST" 
   (	"ID" NUMBER, 
	"NUMBER" VARCHAR2(200 BYTE), 
	"REGISTER" VARCHAR2(100 BYTE), 
	"REGISTER_UNIT" VARCHAR2(200 BYTE), 
	"REGISTER_TITLE" VARCHAR2(200 BYTE), 
	"SW_MODULE" VARCHAR2(2000 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"DEMAND_LEVEL" VARCHAR2(200 BYTE), 
	"ANNEX" VARCHAR2(200 BYTE), 
	"DESCRIBE_INFO" VARCHAR2(2000 BYTE), 
	"DESIRED_RESULT" VARCHAR2(2000 BYTE), 
	"CREATE_DATA" DATE, 
	"CREATOR_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"UPGRADE_SCHEME_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."ID" IS '唯一id标识';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."NUMBER" IS '编号';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."REGISTER" IS '登记人';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."REGISTER_UNIT" IS '登记单位';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."REGISTER_TITLE" IS '日常登记标题';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."SW_MODULE" IS '软件谱系';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."STATE" IS '状态';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."DEMAND_LEVEL" IS '需求等级';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."DESCRIBE_INFO" IS '描述信息';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."DESIRED_RESULT" IS '预期效果';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."CREATE_DATA" IS '创建日期';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."CREATOR_ID" IS '创建人';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."UPDATE_DATE" IS '更新日期';
 
   COMMENT ON COLUMN "P_UPGRADE_REQUEST"."UPDATE_ID" IS '更新人员';
--------------------------------------------------------
--  DDL for Table P_UPGRADE_SCHEME
--------------------------------------------------------

  CREATE TABLE "P_UPGRADE_SCHEME" 
   (	"ID" NUMBER, 
	"CODE" VARCHAR2(200 BYTE), 
	"FORMULATE_UNIT" VARCHAR2(200 BYTE), 
	"SCHEME_NAME" VARCHAR2(200 BYTE), 
	"TASK_SOURSE" VARCHAR2(200 BYTE), 
	"SW_MODULE" VARCHAR2(200 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"ANNEX" VARCHAR2(200 BYTE), 
	"SCHEME_DESCRIBE" VARCHAR2(2000 BYTE), 
	"HANDLER" VARCHAR2(200 BYTE), 
	"TASK_DISTRIBUTION" VARCHAR2(200 BYTE), 
	"DESCRIBE" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."CODE" IS '编号';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."FORMULATE_UNIT" IS '制定单位';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."SCHEME_NAME" IS '方案名称';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."TASK_SOURSE" IS '任务来源';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."SW_MODULE" IS '软件谱系';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."SCHEME_DESCRIBE" IS '方案描述';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."HANDLER" IS '处理人';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."TASK_DISTRIBUTION" IS '分配人';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."DESCRIBE" IS '说明';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_UPGRADE_SCHEME"."UPDATE_ID" IS '更新人员';
--------------------------------------------------------
--  DDL for Table P_UPGRADE_SUMMARY
--------------------------------------------------------

  CREATE TABLE "P_UPGRADE_SUMMARY" 
   (	"ID" NUMBER, 
	"CODE" NUMBER, 
	"STATE" VARCHAR2(200 BYTE), 
	"DESCRIBE_INFO" VARCHAR2(2000 BYTE), 
	"ANNEX" VARCHAR2(200 BYTE), 
	"SUMMARY_UNIT" VARCHAR2(200 BYTE), 
	"COLLECTOR" VARCHAR2(200 BYTE), 
	"SW_MODULE" VARCHAR2(500 BYTE), 
	"SW_NAME" VARCHAR2(200 BYTE), 
	"FAULT_LEVEL" NUMBER, 
	"DESIRED_RESULT" VARCHAR2(2000 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_ID" NUMBER, 
	"UPGRADE_APPLY_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."CODE" IS '编号';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."STATE" IS '状态';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."DESCRIBE_INFO" IS '描述信息';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."ANNEX" IS '附件';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."SUMMARY_UNIT" IS '汇总单位';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."COLLECTOR" IS '汇总人';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."SW_MODULE" IS '谱系';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."FAULT_LEVEL" IS '故障等级：0表示一般，1表示严重';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."DESIRED_RESULT" IS '预期效果';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."CREATE_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."CREATE_ID" IS '创建人员';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."UPDATE_DATE" IS '更新时间';
 
   COMMENT ON COLUMN "P_UPGRADE_SUMMARY"."UPDATE_ID" IS '更新人员';
--------------------------------------------------------
--  DDL for Table SOFTWARE_BASICINFO
--------------------------------------------------------

  CREATE TABLE "SOFTWARE_BASICINFO" 
   (	"ID" NUMBER(11,0), 
	"SW_CODE" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(64 BYTE), 
	"CATEGORY" VARCHAR2(64 BYTE), 
	"MODULE_RELATION" VARCHAR2(64 BYTE), 
	"DEPARTMENT" VARCHAR2(64 BYTE), 
	"SW_OWNER" VARCHAR2(20 BYTE), 
	"SW_SYSTEM" VARCHAR2(64 BYTE), 
	"INSTALLPOS" VARCHAR2(64 BYTE), 
	"SW_STORAGE" VARCHAR2(100 BYTE) DEFAULT 0, 
	"SW_SAVEPOS" VARCHAR2(64 BYTE), 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"MAKEUNIT" VARCHAR2(2000 BYTE), 
	"SW_ANNEX" VARCHAR2(2000 BYTE), 
	"SW_INFO" VARCHAR2(2000 BYTE), 
	"PID" VARCHAR2(20 BYTE), 
	"SW_VERSION" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE, 
	"MD5" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."SW_CODE" IS '软件编号';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."NAME" IS '软件名称';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."CATEGORY" IS '软件谱系';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."MODULE_RELATION" IS '软件模块关系';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."DEPARTMENT" IS '研制单位';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."SW_OWNER" IS '军代表';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."SW_SYSTEM" IS '操作系统';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."INSTALLPOS" IS '典型安装位置';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."SW_STORAGE" IS '存储方式';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."SW_SAVEPOS" IS '存储位置';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."STATUS" IS '激活';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."SW_ANNEX" IS '附件';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."SW_INFO" IS '软件描述';
 
   COMMENT ON COLUMN "SOFTWARE_BASICINFO"."SW_VERSION" IS '软件版本';
--------------------------------------------------------
--  DDL for Table SOFTWARE_CATEGORY
--------------------------------------------------------

  CREATE TABLE "SOFTWARE_CATEGORY" 
   (	"ID" NUMBER(11,0), 
	"SU_CODE" VARCHAR2(64 BYTE), 
	"SU_NAME" VARCHAR2(20 BYTE), 
	"SUPERIOR_ID" NUMBER(11,20), 
	"SW_NAME" VARCHAR2(20 BYTE), 
	"SW_MODULE" VARCHAR2(64 BYTE), 
	"DEPARTMENT" VARCHAR2(64 BYTE), 
	"SU_OWNERID" VARCHAR2(20 BYTE), 
	"SU_SYSTEM" VARCHAR2(20 BYTE), 
	"INSTALLPOS" VARCHAR2(64 BYTE), 
	"SU_STORAGE" NUMBER, 
	"SU_SAVEPOS" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT NULL, 
	"SU_ANNEX" VARCHAR2(64 BYTE), 
	"SU_DESCRIBE" VARCHAR2(2000 BYTE), 
	"UPDATETIME" DATE, 
	"CREATETIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SU_CODE" IS '编号';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SU_NAME" IS '软件单元名称';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SUPERIOR_ID" IS '上级ID';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SW_NAME" IS '软件名称';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SW_MODULE" IS '谱系';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."DEPARTMENT" IS '研制单位';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SU_OWNERID" IS '军代表';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SU_SYSTEM" IS '操作系统';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."INSTALLPOS" IS '安装位置';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SU_STORAGE" IS '存储方式';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SU_SAVEPOS" IS '存储位置';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."STATUS" IS '0可用（激活），1不可用（未激活），2永久删除';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SU_ANNEX" IS '附件';
 
   COMMENT ON COLUMN "SOFTWARE_CATEGORY"."SU_DESCRIBE" IS '软件单元描述';
--------------------------------------------------------
--  DDL for Table SOFTWARE_MODULE
--------------------------------------------------------

  CREATE TABLE "SOFTWARE_MODULE" 
   (	"ID" NUMBER(11,0), 
	"NAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"PARENT_ID" VARCHAR2(500 BYTE) DEFAULT NULL, 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_USER" NUMBER(11,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
 

   COMMENT ON COLUMN "SOFTWARE_MODULE"."ID" IS '软件谱系ID';
 
   COMMENT ON COLUMN "SOFTWARE_MODULE"."NAME" IS '软件谱系名称';
 
   COMMENT ON COLUMN "SOFTWARE_MODULE"."PARENT_ID" IS '父级谱系 ID';
 
   COMMENT ON COLUMN "SOFTWARE_MODULE"."STATUS" IS '0可用（激活），1不可用（未激活），2永久删除';
REM INSERTING into ZYZ.B_BASICINFO
SET DEFINE OFF;
REM INSERTING into ZYZ.B_CATEGORY
SET DEFINE OFF;
REM INSERTING into ZYZ.B_MODULE
SET DEFINE OFF;
REM INSERTING into ZYZ.B_UNIT
SET DEFINE OFF;
REM INSERTING into ZYZ.B_USER
SET DEFINE OFF;
REM INSERTING into ZYZ.P_DAILY_REGISTER
SET DEFINE OFF;
REM INSERTING into ZYZ.P_DEPLOYAPPLY
SET DEFINE OFF;
REM INSERTING into ZYZ.P_DEPLOY_SCHEMA
SET DEFINE OFF;
REM INSERTING into ZYZ.P_EXPORTAPPLY
SET DEFINE OFF;
REM INSERTING into ZYZ.P_HISTORY_RECORD
SET DEFINE OFF;
REM INSERTING into ZYZ.P_ONLINE_HELP
SET DEFINE OFF;
REM INSERTING into ZYZ.P_PLAN
SET DEFINE OFF;
REM INSERTING into ZYZ.P_PLAN_STAGE
SET DEFINE OFF;
REM INSERTING into ZYZ.P_REGISTER_SUMMARY
SET DEFINE OFF;
REM INSERTING into ZYZ.P_RETIREAPPLY
SET DEFINE OFF;
REM INSERTING into ZYZ.P_STORAGEAPPLY
SET DEFINE OFF;
REM INSERTING into ZYZ.P_SUPPORT_SCHEME_TASK
SET DEFINE OFF;
REM INSERTING into ZYZ.P_TECHNICAL_SUPPORT_REQUEST
SET DEFINE OFF;
REM INSERTING into ZYZ.P_TECHNICAL_SUPPORT_SCHEME
SET DEFINE OFF;
REM INSERTING into ZYZ.P_UPGRADE_APPLY
SET DEFINE OFF;
REM INSERTING into ZYZ.P_UPGRADE_REQUEST
SET DEFINE OFF;
REM INSERTING into ZYZ.P_UPGRADE_SCHEME
SET DEFINE OFF;
REM INSERTING into ZYZ.P_UPGRADE_SUMMARY
SET DEFINE OFF;
REM INSERTING into ZYZ.SOFTWARE_BASICINFO
SET DEFINE OFF;
Insert into ZYZ.SOFTWARE_BASICINFO (ID,SW_CODE,NAME,CATEGORY,MODULE_RELATION,DEPARTMENT,SW_OWNER,SW_SYSTEM,INSTALLPOS,SW_STORAGE,SW_SAVEPOS,STATUS,MAKEUNIT,SW_ANNEX,SW_INFO,PID,SW_VERSION,CREATE_TIME,MD5) values (1,'MSSXL0678','声呐定位指示软件','中船-709所','应用软件>C类应用软件>对下声呐定位','中船重工XXX研究所','张三','塞班2.0、CentOS7','中控板、导航板','网络介质/存储介质','中控板、导航板',0,'中船-709所','指导文件1','七○二所，1951年建立于上海黄浦江畔，1965年总部搬迁至无锡，在上海设有分部和青岛分部。数十年来建有功能齐全、配套完整的大中型科研试验设施近30座，设有两个国家级重点实验室，两个国家级检测',null,'v.3.2.35',to_date('10-8月 -17','DD-MON-RR'),'255884778dsia');
Insert into ZYZ.SOFTWARE_BASICINFO (ID,SW_CODE,NAME,CATEGORY,MODULE_RELATION,DEPARTMENT,SW_OWNER,SW_SYSTEM,INSTALLPOS,SW_STORAGE,SW_SAVEPOS,STATUS,MAKEUNIT,SW_ANNEX,SW_INFO,PID,SW_VERSION,CREATE_TIME,MD5) values (2,'MSSXL0678','声呐定位指示软件','中船-709所','应用软件>C类应用软件>对下声呐定位','中船重工XXX研究所','张三','塞班2.0、CentOS7','中控板、导航板','网络介质/存储介质','中控板、导航板',0,'中船-709所','指导文件1','七○二所，1951年建立于上海黄浦江畔，1965年总部搬迁至无锡，在上海设有分部和青岛分部。数十年来建有功能齐全、配套完整的大中型科研试验设施近30座，设有两个国家级重点实验室，两个国家级检测','1','v.3.2.35',to_date('04-6月 -17','DD-MON-RR'),'255884778dsia');
Insert into ZYZ.SOFTWARE_BASICINFO (ID,SW_CODE,NAME,CATEGORY,MODULE_RELATION,DEPARTMENT,SW_OWNER,SW_SYSTEM,INSTALLPOS,SW_STORAGE,SW_SAVEPOS,STATUS,MAKEUNIT,SW_ANNEX,SW_INFO,PID,SW_VERSION,CREATE_TIME,MD5) values (3,'MSSXL0678','声呐定位指示软件','中船-709所','应用软件>C类应用软件>对下声呐定位','中船重工XXX研究所','张三','塞班2.0、CentOS7','中控板、导航板','网络介质/存储介质','中控板、导航板',0,'中船-709所','指导文件1','七○二所，1951年建立于上海黄浦江畔，1965年总部搬迁至无锡，在上海设有分部和青岛分部。数十年来建有功能齐全、配套完整的大中型科研试验设施近30座，设有两个国家级重点实验室，两个国家级检测','1','v.3.2.35',to_date('17-5月 -17','DD-MON-RR'),'255884778dsia');
Insert into ZYZ.SOFTWARE_BASICINFO (ID,SW_CODE,NAME,CATEGORY,MODULE_RELATION,DEPARTMENT,SW_OWNER,SW_SYSTEM,INSTALLPOS,SW_STORAGE,SW_SAVEPOS,STATUS,MAKEUNIT,SW_ANNEX,SW_INFO,PID,SW_VERSION,CREATE_TIME,MD5) values (4,'MSSXL0678','声呐定位指示软件','中船-709所','应用软件>C类应用软件>对下声呐定位','中船重工XXX研究所','张三','塞班2.0、CentOS7','中控板、导航板','网络介质/存储介质','中控板、导航板',0,'中船-709所','指导文件1','七○二所，1951年建立于上海黄浦江畔，1965年总部搬迁至无锡，在上海设有分部和青岛分部。数十年来建有功能齐全、配套完整的大中型科研试验设施近30座，设有两个国家级重点实验室，两个国家级检测','1','v.3.2.35',to_date('05-8月 -17','DD-MON-RR'),'255884778dsia');
Insert into ZYZ.SOFTWARE_BASICINFO (ID,SW_CODE,NAME,CATEGORY,MODULE_RELATION,DEPARTMENT,SW_OWNER,SW_SYSTEM,INSTALLPOS,SW_STORAGE,SW_SAVEPOS,STATUS,MAKEUNIT,SW_ANNEX,SW_INFO,PID,SW_VERSION,CREATE_TIME,MD5) values (5,'MSSXL0678','声呐定位指示软件','中船-709所','应用软件>C类应用软件>对下声呐定位','中船重工XXX研究所','张三','塞班2.0、CentOS7','中控板、导航板','网络介质/存储介质','中控板、导航板',0,'中船-709所','指导文件1','七○二所，1951年建立于上海黄浦江畔，1965年总部搬迁至无锡，在上海设有分部和青岛分部。数十年来建有功能齐全、配套完整的大中型科研试验设施近30座，设有两个国家级重点实验室，两个国家级检测',null,'v.3.2.35',to_date('05-8月 -17','DD-MON-RR'),'255884778dsia');
REM INSERTING into ZYZ.SOFTWARE_CATEGORY
SET DEFINE OFF;
REM INSERTING into ZYZ.SOFTWARE_MODULE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "SOFTWARE_BASICINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index SOFTWARE_UNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFTWARE_UNIT_PK" ON "B_UNIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index PK_P_REGISTER_SUMMARY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_P_REGISTER_SUMMARY" ON "P_REGISTER_SUMMARY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index AK_KEY_1_P_DAILY_
--------------------------------------------------------

  CREATE UNIQUE INDEX "AK_KEY_1_P_DAILY_" ON "P_DAILY_REGISTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index AK_KEY_1_P_PLAN
--------------------------------------------------------

  CREATE UNIQUE INDEX "AK_KEY_1_P_PLAN" ON "P_PLAN" ("PLAN_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index PK_P_SUPPORT_SCHEME_TASK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_P_SUPPORT_SCHEME_TASK" ON "P_SUPPORT_SCHEME_TASK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index PK_P_UPGRADE_SUMMARY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_P_UPGRADE_SUMMARY" ON "P_UPGRADE_SUMMARY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index P_EXPORTAPPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P_EXPORTAPPLY_PK" ON "P_EXPORTAPPLY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index PK_P_UPGRADE_SCHEME
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_P_UPGRADE_SCHEME" ON "P_UPGRADE_SCHEME" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index P_DEPLOY_SCHEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P_DEPLOY_SCHEMA_PK" ON "P_DEPLOY_SCHEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index PK_P_HISTORY_RECORD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_P_HISTORY_RECORD" ON "P_HISTORY_RECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index P_STORAGEAPPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P_STORAGEAPPLY_PK" ON "P_STORAGEAPPLY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index P_DEPLOYAPPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P_DEPLOYAPPLY_PK" ON "P_DEPLOYAPPLY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index AK_KEY_1_P_PLAN_S
--------------------------------------------------------

  CREATE UNIQUE INDEX "AK_KEY_1_P_PLAN_S" ON "P_PLAN_STAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index SOFTWARE_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFTWARE_CATEGORY_PK" ON "SOFTWARE_CATEGORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index PK_P_TECHNICAL_SUPPORT_REQUEST
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_P_TECHNICAL_SUPPORT_REQUEST" ON "P_TECHNICAL_SUPPORT_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index PK_P_ONLINE_HELP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_P_ONLINE_HELP" ON "P_ONLINE_HELP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  DDL for Index PK_P_TECHNICAL_SUPPORT_SCHEME
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_P_TECHNICAL_SUPPORT_SCHEME" ON "P_TECHNICAL_SUPPORT_SCHEME" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE" ;
--------------------------------------------------------
--  Constraints for Table P_STORAGEAPPLY
--------------------------------------------------------

  ALTER TABLE "P_STORAGEAPPLY" ADD CONSTRAINT "P_STORAGEAPPLY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE"  ENABLE;
 
  ALTER TABLE "P_STORAGEAPPLY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOFTWARE_BASICINFO
--------------------------------------------------------

  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("SW_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("CATEGORY" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("MODULE_RELATION" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("DEPARTMENT" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("SW_OWNER" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("SW_SYSTEM" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("INSTALLPOS" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("SW_STORAGE" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("SW_SAVEPOS" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" MODIFY ("MAKEUNIT" NOT NULL ENABLE);
 
  ALTER TABLE "SOFTWARE_BASICINFO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFTWARE_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table P_DAILY_REGISTER
--------------------------------------------------------

  ALTER TABLE "P_DAILY_REGISTER" ADD CONSTRAINT "AK_KEY_1_P_DAILY_" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table P_UPGRADE_SCHEME
--------------------------------------------------------

  ALTER TABLE "P_UPGRADE_SCHEME" ADD CONSTRAINT "PK_P_UPGRADE_SCHEME" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE"  ENABLE;
 
  ALTER TABLE "P_UPGRADE_SCHEME" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table P_PLAN
--------------------------------------------------------

  ALTER TABLE "P_PLAN" ADD CONSTRAINT "AK_KEY_1_P_PLAN" UNIQUE ("PLAN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOFTWARE_MODULE
--------------------------------------------------------

  ALTER TABLE "SOFTWARE_MODULE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table P_HISTORY_RECORD
--------------------------------------------------------

  ALTER TABLE "P_HISTORY_RECORD" ADD CONSTRAINT "PK_P_HISTORY_RECORD" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE"  ENABLE;
 
  ALTER TABLE "P_HISTORY_RECORD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table P_TECHNICAL_SUPPORT_REQUEST
--------------------------------------------------------

  ALTER TABLE "P_TECHNICAL_SUPPORT_REQUEST" ADD CONSTRAINT "PK_P_TECHNICAL_SUPPORT_REQUEST" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SOFTWARE_SPACE"  ENABLE;
 
  ALTER TABLE "P_TECHNICAL_SUPPORT_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
